# Generated by Django 4.0.3 on 2022-07-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.CharField(max_length=250),
        ),
    ]
